---
title: "Rowley_Apr30"
author: "Brock Rowley"
date: "4/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lme4)
library(performance)
library(lubridate)
library(sundry)
library(nlme)

cnlsy <- read_csv(here::here("data", "cnlsy.csv"))
wages <- read_csv(here::here("data", "wages.csv"))
sim_d <- read_csv(here::here("data", "curvilinear-sim.csv"))
sim3 <- read_csv(here::here("data", "sim3level.csv"))
willett <- read_csv(here::here("data", "willett-1988.csv"))

```
```{r translate}
head(sleepstudy)

lmer(Reaction ~ 1 + (1|Subject), data = sleepstudy)

lmer(Reaction ~ Days + (1|Subject), data = sleepstudy)

lmer(Reaction ~ Days + (Days|Subject), data = sleepstudy)

sim3 %>% 
  count(Classroom, School)

sim3 <- sim3 %>%
  mutate(class_id = paste0("class", Classroom, ":", School))
sim3

#New Model
lmer(Math ~ ActiveTime + (ActiveTime|class_id) + (1|School), data = sim3)

lmer(Math ~ ActiveTime + ClassSize + (ActiveTime|class_id) + (ActiveTime|School), data = sim3)

lmer(Math ~ ActiveTime * ClassSize + (ActiveTime|class_id) + (ActiveTime + ClassSize|School), data = sim3)
```

```{r willett}
bad <- lm(opp ~ time, data = willett)
summary(bad)

w0 <- lmer(opp ~ time + (1|id), willett)

w0_rvcv <- pull_residual_vcov(w0)
image(w0_rvcv)

w0_rvcv[1:8, 1:8]
arm::display(w0)

vars_w0 <- as.data.frame(VarCorr(w0))
vars_w0

#Unstructured
#The model we fit has an unstructured variance co-variance matrix. While each
#block is the same, every element of the block is now estimated.

w1 <- lmer(opp ~ time + (time|id), willett)
w1_rvcv <- pull_residual_vcov(w1)
w1_rvcv[1:4, 1:4]

vars_w1 <- as.data.frame(VarCorr(w1))

# get the pieces
int_var <- vars_w1$vcov[1]
slope_var <- vars_w1$vcov[2]
covar <- vars_w1$vcov[3]
residual <- vars_w1$vcov[4]

diag(w1_rvcv[1:4, 1:4])

residual + int_var

residual + int_var + 2*covar + slope_var

residual + int_var + (2*covar)*2 + slope_var*2^2

residual + int_var + (2*covar)*3 + slope_var*3^2

w1_rvcv[1:4, 1:4]
int_var + covar*(1 + 0) + slope_var*1*0
int_var + covar*(2 + 1) + slope_var*2*1
int_var + covar*(3 + 2) + slope_var*3*2
```
```{r one_hot}
w <- willett %>%
  mutate(t0 = ifelse(time == 0, 1, 0),
         t1 = ifelse(time == 1, 1, 0),
         t2 = ifelse(time == 2, 1, 0),
         t3 = ifelse(time == 3, 1, 0))

model.matrix( ~ 0 + factor(time), data = willett) %>% 
  head()
# Fit the model
varcomp <- lmer(opp ~  time + (0 + t0 + t1 + t2 + t3 || id), w)
summary(varcomp)

sundry::pull_residual_vcov(varcomp)[1:4, 1:4]
```

```{r fully_unstructured}
# Model check and number of random effects == observations.
fully_unstructured <- lmer(opp ~  time + 
                             (0 + t0 + t1 + t2 + t3 | id), 
                           data = w)

#We can still estimate, just tell the model to ignore this check
fully_unstructured <- lmer(
  opp ~  time + (0 + t0 + t1 + t2 + t3 | id), 
  data = w,
  control = lmerControl(check.nobs.vs.nRE = "ignore")
)
arm::display(fully_unstructured)
```

```{r autoregressive}
ar <- gls(opp ~ time,
          data = willett,
          correlation = corAR1(form = ~ 1|id))
summary(ar)

#Extract composite residual
cm_ar <- corMatrix(ar$modelStruct$corStruct) # all of them
cr_ar <- cm_ar[[1]] # just the first (they're all the same)
cr_ar

#Multiply the correlation matrix by the model residual variance to get the covariance matrix
cr_ar * sigma(ar)^2

#Confirming calculations
sigma(ar)^2
sigma(ar)^2*0.8249118
sigma(ar)^2*0.8249118^2
sigma(ar)^2*0.8249118^3
```

```{r reference_code}
har <- gls(
  opp ~ time,
  data = willett,
  correlation = corAR1(form = ~ 1|id),
  weights = varIdent(form = ~1|time) # different weights by time
)
summary(har)

cm_har <- corMatrix(har$modelStruct$corStruct)[[1]]
var_struct <- har$modelStruct$varStruct
vars <- coef(var_struct, unconstrained = FALSE, allCoef = TRUE)
vars <- matrix(vars, ncol = 1)
cm_har * sigma(har)^2 * 
  (vars %*% t(vars)) # multiply by a mat of vars
```

```{r toeplitz}
toep <- gls(opp ~ time,
            data = willett,
            correlation = corARMA(form = ~ 1|id, p = 3))
summary(toep)

# Extract/compute composite residual
cr_toep <- corMatrix(toep$modelStruct$corStruct)[[1]]
cr_toep * sigma(toep)^2
```

```{r comparing_fits}
compare_performance(ar, har, toep, w1, varcomp, fully_unstructured,
                    metrics = c("AIC", "BIC"),
                    rank = TRUE) %>%
  as_tibble()
```
